name: 'Bit Pull Request'
description: 'Build components, snap and update lane for Pull Requests'
branding: 
  icon: 'git-pull-request'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
  version-labels:
      description: "Include semantic version labels for new/modified components"
      required: false
  version-labels-color:
      description: "Specify the hex color code for automatically created version labels."
      required: false
      default: "6f42c1"
runs:
  using: 'node20'
  main: 'dist/index.js'

