name: Test Bit Pull Request with Docker
on:
  workflow_dispatch:   # Manual trigger
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bitsrc/stable:latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_CONFIG_ACCESS_TOKEN }}
    steps:
      - name: Create symlink to _w directory
        run: |
          mkdir -p /home/runner
          ln -sfn /__w /home/runner/work
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize Bit
        uses: bit-tasks/init@v2
        with:
            ws-dir: 'test-data'
      - name: Creating a bare scope
        run: mkdir bit-tasks.test-scope && cd bit-tasks.test-scope && bit init --bare
      - name: Start the server and test
        run: cd bit-tasks.test-scope && bit start --port 4000 --no-browser & sleep 200 && curl http://localhost:4000 
      - name: Add remote scope
        run: cd test-data && bit remote add http://localhost:4000   
      - name: Bit Pull Request
        uses: bit-tasks/pull-request@main
      - name: Bit Lanes
        run: cd test-data && bit lane list --details
